language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
script:
  # - yarn run prettier:check
  - yarn build

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/gh-pages -d public; fi
